### PR TITLE
Enhance links (UX)

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Goodbye ExtJS4 😎

**Comment by dnsmichi** [comment]
The icon set works like a charm.

screen shot 2018-03-13 at 13 51 36


```
Plugin('RTx::CreateLinkedTickets');

Set($RTx_CreateLinkedTickets_Config, [
        {
                name            => 'clt-billing',
                icon            => 'cart-plus',
                title           => 'Create Billing Ticket',
                template        => 'CLT-Billing'
        },
        {
                name            => 'clt-eventattendee',
                icon            => 'calendar',
                title           => 'Create Event Attendee',
                template        => 'CLT-EventAttendee'
        }

]);
```

# TODOs

- JS popup if one really wants to create such ticket (based on JQuery)
- Icons instead of text blocks
- Docs

**Review by dnsmichi — CHANGES_REQUESTED** [review]
See above.

**Comment by dnsmichi** [comment]
Works fine, thanks 👍 

screen shot 2018-03-13 at 17 37 41

screen shot 2018-03-13 at 17 37 45

**Review by dnsmichi — APPROVED** [review]

**Comment by dnsmichi** [comment]
Docs are needed :)

**Pull request merged**
